//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Wix3.Difxapp {

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/DifxAppExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/DifxAppExtension", IsNullable = false)]
  public partial class Driver {

    private YesNoType addRemoveProgramsField;

    private bool addRemoveProgramsFieldSpecified;

    private YesNoType deleteFilesField;

    private bool deleteFilesFieldSpecified;

    private YesNoType forceInstallField;

    private bool forceInstallFieldSpecified;

    private YesNoType legacyField;

    private bool legacyFieldSpecified;

    private YesNoType plugAndPlayPromptField;

    private bool plugAndPlayPromptFieldSpecified;

    private string sequenceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType AddRemovePrograms {
      get {
        return this.addRemoveProgramsField;
      }
      set {
        this.addRemoveProgramsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AddRemoveProgramsSpecified {
      get {
        return this.addRemoveProgramsFieldSpecified;
      }
      set {
        this.addRemoveProgramsFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType DeleteFiles {
      get {
        return this.deleteFilesField;
      }
      set {
        this.deleteFilesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeleteFilesSpecified {
      get {
        return this.deleteFilesFieldSpecified;
      }
      set {
        this.deleteFilesFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ForceInstall {
      get {
        return this.forceInstallField;
      }
      set {
        this.forceInstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ForceInstallSpecified {
      get {
        return this.forceInstallFieldSpecified;
      }
      set {
        this.forceInstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Legacy {
      get {
        return this.legacyField;
      }
      set {
        this.legacyField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LegacySpecified {
      get {
        return this.legacyFieldSpecified;
      }
      set {
        this.legacyFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType PlugAndPlayPrompt {
      get {
        return this.plugAndPlayPromptField;
      }
      set {
        this.plugAndPlayPromptField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PlugAndPlayPromptSpecified {
      get {
        return this.plugAndPlayPromptFieldSpecified;
      }
      set {
        this.plugAndPlayPromptFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string Sequence {
      get {
        return this.sequenceField;
      }
      set {
        this.sequenceField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/wix/DifxAppExtension")]
  public enum YesNoType {

    /// <remarks/>
    no,

    /// <remarks/>
    yes,
  }
}