//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Wix3.Firewall {

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/FirewallExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/FirewallExtension", IsNullable = false)]
  public partial class FirewallException {

    private RemoteAddress[] itemsField;

    private string idField;

    private string nameField;

    private FirewallExceptionScope scopeField;

    private bool scopeFieldSpecified;

    private string portField;

    private FirewallExceptionProtocol protocolField;

    private bool protocolFieldSpecified;

    private string fileField;

    private string programField;

    private YesNoType ignoreFailureField;

    private bool ignoreFailureFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RemoteAddress")]
    public RemoteAddress[] Items {
      get {
        return this.itemsField;
      }
      set {
        this.itemsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public FirewallExceptionScope Scope {
      get {
        return this.scopeField;
      }
      set {
        this.scopeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ScopeSpecified {
      get {
        return this.scopeFieldSpecified;
      }
      set {
        this.scopeFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Port {
      get {
        return this.portField;
      }
      set {
        this.portField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public FirewallExceptionProtocol Protocol {
      get {
        return this.protocolField;
      }
      set {
        this.protocolField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ProtocolSpecified {
      get {
        return this.protocolFieldSpecified;
      }
      set {
        this.protocolFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string File {
      get {
        return this.fileField;
      }
      set {
        this.fileField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Program {
      get {
        return this.programField;
      }
      set {
        this.programField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType IgnoreFailure {
      get {
        return this.ignoreFailureField;
      }
      set {
        this.ignoreFailureField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IgnoreFailureSpecified {
      get {
        return this.ignoreFailureFieldSpecified;
      }
      set {
        this.ignoreFailureFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/FirewallExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/FirewallExtension", IsNullable = false)]
  public partial class RemoteAddress {

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
      get {
        return this.valueField;
      }
      set {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/FirewallExtension")]
  public enum FirewallExceptionScope {

    /// <remarks/>
    any,

    /// <remarks/>
    localSubnet,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/FirewallExtension")]
  public enum FirewallExceptionProtocol {

    /// <remarks/>
    tcp,

    /// <remarks/>
    udp,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/wix/FirewallExtension")]
  public enum YesNoType {

    /// <remarks/>
    no,

    /// <remarks/>
    yes,
  }
}