//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Wix3.Iis {

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension", IsNullable = false)]
  public partial class WebDirProperties {

    private string idField;

    private YesNoType readField;

    private bool readFieldSpecified;

    private YesNoType writeField;

    private bool writeFieldSpecified;

    private YesNoType scriptField;

    private bool scriptFieldSpecified;

    private YesNoType executeField;

    private bool executeFieldSpecified;

    private YesNoType anonymousAccessField;

    private bool anonymousAccessFieldSpecified;

    private string anonymousUserField;

    private YesNoType iIsControlledPasswordField;

    private bool iIsControlledPasswordFieldSpecified;

    private YesNoType windowsAuthenticationField;

    private bool windowsAuthenticationFieldSpecified;

    private YesNoType digestAuthenticationField;

    private bool digestAuthenticationFieldSpecified;

    private YesNoType basicAuthenticationField;

    private bool basicAuthenticationFieldSpecified;

    private YesNoType passportAuthenticationField;

    private bool passportAuthenticationFieldSpecified;

    private YesNoType logVisitsField;

    private bool logVisitsFieldSpecified;

    private YesNoType indexField;

    private bool indexFieldSpecified;

    private string defaultDocumentsField;

    private YesNoType aspDetailedErrorField;

    private bool aspDetailedErrorFieldSpecified;

    private string httpExpiresField;

    private string cacheControlMaxAgeField;

    private string cacheControlCustomField;

    private YesNoType clearCustomErrorField;

    private bool clearCustomErrorFieldSpecified;

    private YesNoType accessSSLField;

    private bool accessSSLFieldSpecified;

    private YesNoType accessSSL128Field;

    private bool accessSSL128FieldSpecified;

    private YesNoType accessSSLMapCertField;

    private bool accessSSLMapCertFieldSpecified;

    private YesNoType accessSSLNegotiateCertField;

    private bool accessSSLNegotiateCertFieldSpecified;

    private YesNoType accessSSLRequireCertField;

    private bool accessSSLRequireCertFieldSpecified;

    private string authenticationProvidersField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Read {
      get {
        return this.readField;
      }
      set {
        this.readField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReadSpecified {
      get {
        return this.readFieldSpecified;
      }
      set {
        this.readFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Write {
      get {
        return this.writeField;
      }
      set {
        this.writeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WriteSpecified {
      get {
        return this.writeFieldSpecified;
      }
      set {
        this.writeFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Script {
      get {
        return this.scriptField;
      }
      set {
        this.scriptField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ScriptSpecified {
      get {
        return this.scriptFieldSpecified;
      }
      set {
        this.scriptFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Execute {
      get {
        return this.executeField;
      }
      set {
        this.executeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExecuteSpecified {
      get {
        return this.executeFieldSpecified;
      }
      set {
        this.executeFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType AnonymousAccess {
      get {
        return this.anonymousAccessField;
      }
      set {
        this.anonymousAccessField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AnonymousAccessSpecified {
      get {
        return this.anonymousAccessFieldSpecified;
      }
      set {
        this.anonymousAccessFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AnonymousUser {
      get {
        return this.anonymousUserField;
      }
      set {
        this.anonymousUserField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType IIsControlledPassword {
      get {
        return this.iIsControlledPasswordField;
      }
      set {
        this.iIsControlledPasswordField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IIsControlledPasswordSpecified {
      get {
        return this.iIsControlledPasswordFieldSpecified;
      }
      set {
        this.iIsControlledPasswordFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType WindowsAuthentication {
      get {
        return this.windowsAuthenticationField;
      }
      set {
        this.windowsAuthenticationField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WindowsAuthenticationSpecified {
      get {
        return this.windowsAuthenticationFieldSpecified;
      }
      set {
        this.windowsAuthenticationFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType DigestAuthentication {
      get {
        return this.digestAuthenticationField;
      }
      set {
        this.digestAuthenticationField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DigestAuthenticationSpecified {
      get {
        return this.digestAuthenticationFieldSpecified;
      }
      set {
        this.digestAuthenticationFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType BasicAuthentication {
      get {
        return this.basicAuthenticationField;
      }
      set {
        this.basicAuthenticationField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BasicAuthenticationSpecified {
      get {
        return this.basicAuthenticationFieldSpecified;
      }
      set {
        this.basicAuthenticationFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType PassportAuthentication {
      get {
        return this.passportAuthenticationField;
      }
      set {
        this.passportAuthenticationField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PassportAuthenticationSpecified {
      get {
        return this.passportAuthenticationFieldSpecified;
      }
      set {
        this.passportAuthenticationFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType LogVisits {
      get {
        return this.logVisitsField;
      }
      set {
        this.logVisitsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LogVisitsSpecified {
      get {
        return this.logVisitsFieldSpecified;
      }
      set {
        this.logVisitsFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Index {
      get {
        return this.indexField;
      }
      set {
        this.indexField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IndexSpecified {
      get {
        return this.indexFieldSpecified;
      }
      set {
        this.indexFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DefaultDocuments {
      get {
        return this.defaultDocumentsField;
      }
      set {
        this.defaultDocumentsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType AspDetailedError {
      get {
        return this.aspDetailedErrorField;
      }
      set {
        this.aspDetailedErrorField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AspDetailedErrorSpecified {
      get {
        return this.aspDetailedErrorFieldSpecified;
      }
      set {
        this.aspDetailedErrorFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string HttpExpires {
      get {
        return this.httpExpiresField;
      }
      set {
        this.httpExpiresField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
    public string CacheControlMaxAge {
      get {
        return this.cacheControlMaxAgeField;
      }
      set {
        this.cacheControlMaxAgeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CacheControlCustom {
      get {
        return this.cacheControlCustomField;
      }
      set {
        this.cacheControlCustomField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ClearCustomError {
      get {
        return this.clearCustomErrorField;
      }
      set {
        this.clearCustomErrorField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ClearCustomErrorSpecified {
      get {
        return this.clearCustomErrorFieldSpecified;
      }
      set {
        this.clearCustomErrorFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType AccessSSL {
      get {
        return this.accessSSLField;
      }
      set {
        this.accessSSLField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AccessSSLSpecified {
      get {
        return this.accessSSLFieldSpecified;
      }
      set {
        this.accessSSLFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType AccessSSL128 {
      get {
        return this.accessSSL128Field;
      }
      set {
        this.accessSSL128Field = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AccessSSL128Specified {
      get {
        return this.accessSSL128FieldSpecified;
      }
      set {
        this.accessSSL128FieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType AccessSSLMapCert {
      get {
        return this.accessSSLMapCertField;
      }
      set {
        this.accessSSLMapCertField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AccessSSLMapCertSpecified {
      get {
        return this.accessSSLMapCertFieldSpecified;
      }
      set {
        this.accessSSLMapCertFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType AccessSSLNegotiateCert {
      get {
        return this.accessSSLNegotiateCertField;
      }
      set {
        this.accessSSLNegotiateCertField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AccessSSLNegotiateCertSpecified {
      get {
        return this.accessSSLNegotiateCertFieldSpecified;
      }
      set {
        this.accessSSLNegotiateCertFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType AccessSSLRequireCert {
      get {
        return this.accessSSLRequireCertField;
      }
      set {
        this.accessSSLRequireCertField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AccessSSLRequireCertSpecified {
      get {
        return this.accessSSLRequireCertFieldSpecified;
      }
      set {
        this.accessSSLRequireCertFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AuthenticationProviders {
      get {
        return this.authenticationProvidersField;
      }
      set {
        this.authenticationProvidersField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  public enum YesNoType {

    /// <remarks/>
    no,

    /// <remarks/>
    yes,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension", IsNullable = false)]
  public partial class WebError {

    private string errorCodeField;

    private string subCodeField;

    private string fileField;

    private string uRLField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string ErrorCode {
      get {
        return this.errorCodeField;
      }
      set {
        this.errorCodeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string SubCode {
      get {
        return this.subCodeField;
      }
      set {
        this.subCodeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string File {
      get {
        return this.fileField;
      }
      set {
        this.fileField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string URL {
      get {
        return this.uRLField;
      }
      set {
        this.uRLField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension", IsNullable = false)]
  public partial class HttpHeader {

    private string idField;

    private string nameField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
      get {
        return this.valueField;
      }
      set {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension", IsNullable = false)]
  public partial class MimeMap {

    private string idField;

    private string typeField;

    private string extensionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type {
      get {
        return this.typeField;
      }
      set {
        this.typeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Extension {
      get {
        return this.extensionField;
      }
      set {
        this.extensionField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension", IsNullable = false)]
  public partial class WebFilter {

    private string idField;

    private string nameField;

    private string pathField;

    private string webSiteField;

    private string descriptionField;

    private string flagsField;

    private string loadOrderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Path {
      get {
        return this.pathField;
      }
      set {
        this.pathField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string WebSite {
      get {
        return this.webSiteField;
      }
      set {
        this.webSiteField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
      get {
        return this.descriptionField;
      }
      set {
        this.descriptionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string Flags {
      get {
        return this.flagsField;
      }
      set {
        this.flagsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LoadOrder {
      get {
        return this.loadOrderField;
      }
      set {
        this.loadOrderField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension", IsNullable = false)]
  public partial class WebApplicationExtension {

    private string executableField;

    private string extensionField;

    private string verbsField;

    private YesNoType scriptField;

    private bool scriptFieldSpecified;

    private YesNoType checkPathField;

    private bool checkPathFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Executable {
      get {
        return this.executableField;
      }
      set {
        this.executableField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Extension {
      get {
        return this.extensionField;
      }
      set {
        this.extensionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Verbs {
      get {
        return this.verbsField;
      }
      set {
        this.verbsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Script {
      get {
        return this.scriptField;
      }
      set {
        this.scriptField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ScriptSpecified {
      get {
        return this.scriptFieldSpecified;
      }
      set {
        this.scriptFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType CheckPath {
      get {
        return this.checkPathField;
      }
      set {
        this.checkPathField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CheckPathSpecified {
      get {
        return this.checkPathFieldSpecified;
      }
      set {
        this.checkPathFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension", IsNullable = false)]
  public partial class WebAppPool {

    private RecycleTime[] recycleTimeField;

    private string idField;

    private string nameField;

    private string userField;

    private string recycleMinutesField;

    private string recycleRequestsField;

    private string virtualMemoryField;

    private string privateMemoryField;

    private string idleTimeoutField;

    private string queueLimitField;

    private string maxCpuUsageField;

    private string refreshCpuField;

    private WebAppPoolCpuAction cpuActionField;

    private bool cpuActionFieldSpecified;

    private string maxWorkerProcessesField;

    private WebAppPoolIdentity identityField;

    private bool identityFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RecycleTime")]
    public RecycleTime[] RecycleTime {
      get {
        return this.recycleTimeField;
      }
      set {
        this.recycleTimeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string User {
      get {
        return this.userField;
      }
      set {
        this.userField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string RecycleMinutes {
      get {
        return this.recycleMinutesField;
      }
      set {
        this.recycleMinutesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string RecycleRequests {
      get {
        return this.recycleRequestsField;
      }
      set {
        this.recycleRequestsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string VirtualMemory {
      get {
        return this.virtualMemoryField;
      }
      set {
        this.virtualMemoryField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string PrivateMemory {
      get {
        return this.privateMemoryField;
      }
      set {
        this.privateMemoryField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string IdleTimeout {
      get {
        return this.idleTimeoutField;
      }
      set {
        this.idleTimeoutField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string QueueLimit {
      get {
        return this.queueLimitField;
      }
      set {
        this.queueLimitField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
    public string MaxCpuUsage {
      get {
        return this.maxCpuUsageField;
      }
      set {
        this.maxCpuUsageField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string RefreshCpu {
      get {
        return this.refreshCpuField;
      }
      set {
        this.refreshCpuField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public WebAppPoolCpuAction CpuAction {
      get {
        return this.cpuActionField;
      }
      set {
        this.cpuActionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CpuActionSpecified {
      get {
        return this.cpuActionFieldSpecified;
      }
      set {
        this.cpuActionFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string MaxWorkerProcesses {
      get {
        return this.maxWorkerProcessesField;
      }
      set {
        this.maxWorkerProcessesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public WebAppPoolIdentity Identity {
      get {
        return this.identityField;
      }
      set {
        this.identityField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IdentitySpecified {
      get {
        return this.identityFieldSpecified;
      }
      set {
        this.identityFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension", IsNullable = false)]
  public partial class RecycleTime {

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
      get {
        return this.valueField;
      }
      set {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  public enum WebAppPoolCpuAction {

    /// <remarks/>
    none,

    /// <remarks/>
    shutdown,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  public enum WebAppPoolIdentity {

    /// <remarks/>
    networkService,

    /// <remarks/>
    localService,

    /// <remarks/>
    localSystem,

    /// <remarks/>
    other,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension", IsNullable = false)]
  public partial class Certificate {

    private string idField;

    private string nameField;

    private CertificateStoreName storeNameField;

    private CertificateStoreLocation storeLocationField;

    private YesNoType overwriteField;

    private bool overwriteFieldSpecified;

    private YesNoType requestField;

    private bool requestFieldSpecified;

    private string binaryKeyField;

    private string certificatePathField;

    private string pFXPasswordField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public CertificateStoreName StoreName {
      get {
        return this.storeNameField;
      }
      set {
        this.storeNameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public CertificateStoreLocation StoreLocation {
      get {
        return this.storeLocationField;
      }
      set {
        this.storeLocationField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Overwrite {
      get {
        return this.overwriteField;
      }
      set {
        this.overwriteField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OverwriteSpecified {
      get {
        return this.overwriteFieldSpecified;
      }
      set {
        this.overwriteFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Request {
      get {
        return this.requestField;
      }
      set {
        this.requestField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RequestSpecified {
      get {
        return this.requestFieldSpecified;
      }
      set {
        this.requestFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BinaryKey {
      get {
        return this.binaryKeyField;
      }
      set {
        this.binaryKeyField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CertificatePath {
      get {
        return this.certificatePathField;
      }
      set {
        this.certificatePathField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PFXPassword {
      get {
        return this.pFXPasswordField;
      }
      set {
        this.pFXPasswordField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  public enum CertificateStoreName {

    /// <remarks/>
    ca,

    /// <remarks/>
    my,

    /// <remarks/>
    personal,

    /// <remarks/>
    request,

    /// <remarks/>
    root,

    /// <remarks/>
    otherPeople,

    /// <remarks/>
    trustedPeople,

    /// <remarks/>
    trustedPublisher,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  public enum CertificateStoreLocation {

    /// <remarks/>
    currentUser,

    /// <remarks/>
    localMachine,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension", IsNullable = false)]
  public partial class CertificateRef {

    private string idField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension", IsNullable = false)]
  public partial class WebProperty {

    private WebPropertyID idField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public WebPropertyID Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
      get {
        return this.valueField;
      }
      set {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  public enum WebPropertyID {

    /// <remarks/>
    ETagChangeNumber,

    /// <remarks/>
    IIs5IsolationMode,

    /// <remarks/>
    MaxGlobalBandwidth,

    /// <remarks/>
    LogInUTF8,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension", IsNullable = false)]
  public partial class WebApplication {

    private WebApplicationExtension[] webApplicationExtensionField;

    private string idField;

    private string nameField;

    private WebApplicationIsolation isolationField;

    private bool isolationFieldSpecified;

    private YesNoDefaultType allowSessionsField;

    private bool allowSessionsFieldSpecified;

    private string sessionTimeoutField;

    private YesNoDefaultType bufferField;

    private bool bufferFieldSpecified;

    private YesNoDefaultType parentPathsField;

    private bool parentPathsFieldSpecified;

    private WebApplicationDefaultScript defaultScriptField;

    private bool defaultScriptFieldSpecified;

    private string scriptTimeoutField;

    private YesNoDefaultType serverDebuggingField;

    private bool serverDebuggingFieldSpecified;

    private YesNoDefaultType clientDebuggingField;

    private bool clientDebuggingFieldSpecified;

    private string webAppPoolField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("WebApplicationExtension")]
    public WebApplicationExtension[] WebApplicationExtension {
      get {
        return this.webApplicationExtensionField;
      }
      set {
        this.webApplicationExtensionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public WebApplicationIsolation Isolation {
      get {
        return this.isolationField;
      }
      set {
        this.isolationField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsolationSpecified {
      get {
        return this.isolationFieldSpecified;
      }
      set {
        this.isolationFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoDefaultType AllowSessions {
      get {
        return this.allowSessionsField;
      }
      set {
        this.allowSessionsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AllowSessionsSpecified {
      get {
        return this.allowSessionsFieldSpecified;
      }
      set {
        this.allowSessionsFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string SessionTimeout {
      get {
        return this.sessionTimeoutField;
      }
      set {
        this.sessionTimeoutField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoDefaultType Buffer {
      get {
        return this.bufferField;
      }
      set {
        this.bufferField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BufferSpecified {
      get {
        return this.bufferFieldSpecified;
      }
      set {
        this.bufferFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoDefaultType ParentPaths {
      get {
        return this.parentPathsField;
      }
      set {
        this.parentPathsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ParentPathsSpecified {
      get {
        return this.parentPathsFieldSpecified;
      }
      set {
        this.parentPathsFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public WebApplicationDefaultScript DefaultScript {
      get {
        return this.defaultScriptField;
      }
      set {
        this.defaultScriptField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DefaultScriptSpecified {
      get {
        return this.defaultScriptFieldSpecified;
      }
      set {
        this.defaultScriptFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string ScriptTimeout {
      get {
        return this.scriptTimeoutField;
      }
      set {
        this.scriptTimeoutField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoDefaultType ServerDebugging {
      get {
        return this.serverDebuggingField;
      }
      set {
        this.serverDebuggingField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ServerDebuggingSpecified {
      get {
        return this.serverDebuggingFieldSpecified;
      }
      set {
        this.serverDebuggingFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoDefaultType ClientDebugging {
      get {
        return this.clientDebuggingField;
      }
      set {
        this.clientDebuggingField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ClientDebuggingSpecified {
      get {
        return this.clientDebuggingFieldSpecified;
      }
      set {
        this.clientDebuggingFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string WebAppPool {
      get {
        return this.webAppPoolField;
      }
      set {
        this.webAppPoolField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  public enum WebApplicationIsolation {

    /// <remarks/>
    low,

    /// <remarks/>
    medium,

    /// <remarks/>
    high,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  public enum YesNoDefaultType {

    /// <remarks/>
    @default,

    /// <remarks/>
    no,

    /// <remarks/>
    yes,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  public enum WebApplicationDefaultScript {

    /// <remarks/>
    VBScript,

    /// <remarks/>
    JScript,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension", IsNullable = false)]
  public partial class WebAddress {

    private string idField;

    private string ipField;

    private string portField;

    private string headerField;

    private YesNoType secureField;

    private bool secureFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IP {
      get {
        return this.ipField;
      }
      set {
        this.ipField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Port {
      get {
        return this.portField;
      }
      set {
        this.portField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Header {
      get {
        return this.headerField;
      }
      set {
        this.headerField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Secure {
      get {
        return this.secureField;
      }
      set {
        this.secureField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SecureSpecified {
      get {
        return this.secureFieldSpecified;
      }
      set {
        this.secureFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension", IsNullable = false)]
  public partial class WebVirtualDir {

    private object[] itemsField;

    private string idField;

    private string webSiteField;

    private string aliasField;

    private string directoryField;

    private string dirPropertiesField;

    private string webApplicationField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("HttpHeader", typeof(HttpHeader))]
    [System.Xml.Serialization.XmlElementAttribute("MimeMap", typeof(MimeMap))]
    [System.Xml.Serialization.XmlElementAttribute("WebApplication", typeof(WebApplication))]
    [System.Xml.Serialization.XmlElementAttribute("WebDirProperties", typeof(WebDirProperties))]
    [System.Xml.Serialization.XmlElementAttribute("WebError", typeof(WebError))]
    [System.Xml.Serialization.XmlElementAttribute("WebVirtualDir", typeof(WebVirtualDir))]
    public object[] Items {
      get {
        return this.itemsField;
      }
      set {
        this.itemsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string WebSite {
      get {
        return this.webSiteField;
      }
      set {
        this.webSiteField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Alias {
      get {
        return this.aliasField;
      }
      set {
        this.aliasField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Directory {
      get {
        return this.directoryField;
      }
      set {
        this.directoryField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DirProperties {
      get {
        return this.dirPropertiesField;
      }
      set {
        this.dirPropertiesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string WebApplication {
      get {
        return this.webApplicationField;
      }
      set {
        this.webApplicationField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension", IsNullable = false)]
  public partial class WebDir {

    private WebDirProperties itemField;

    private string idField;

    private string webSiteField;

    private string pathField;

    private string dirPropertiesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("WebDirProperties")]
    public WebDirProperties Item {
      get {
        return this.itemField;
      }
      set {
        this.itemField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string WebSite {
      get {
        return this.webSiteField;
      }
      set {
        this.webSiteField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Path {
      get {
        return this.pathField;
      }
      set {
        this.pathField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DirProperties {
      get {
        return this.dirPropertiesField;
      }
      set {
        this.dirPropertiesField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension", IsNullable = false)]
  public partial class WebSite {

    private object[] itemsField;

    private string idField;

    private YesNoType autoStartField;

    private bool autoStartFieldSpecified;

    private YesNoType configureIfExistsField;

    private bool configureIfExistsFieldSpecified;

    private string connectionTimeoutField;

    private string descriptionField;

    private string directoryField;

    private string dirPropertiesField;

    private string sequenceField;

    private string siteIdField;

    private YesNoType startOnInstallField;

    private bool startOnInstallFieldSpecified;

    private string webApplicationField;

    private string webLogField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CertificateRef", typeof(CertificateRef))]
    [System.Xml.Serialization.XmlElementAttribute("HttpHeader", typeof(HttpHeader))]
    [System.Xml.Serialization.XmlElementAttribute("MimeMap", typeof(MimeMap))]
    [System.Xml.Serialization.XmlElementAttribute("WebAddress", typeof(WebAddress))]
    [System.Xml.Serialization.XmlElementAttribute("WebApplication", typeof(WebApplication))]
    [System.Xml.Serialization.XmlElementAttribute("WebDir", typeof(WebDir))]
    [System.Xml.Serialization.XmlElementAttribute("WebDirProperties", typeof(WebDirProperties))]
    [System.Xml.Serialization.XmlElementAttribute("WebError", typeof(WebError))]
    [System.Xml.Serialization.XmlElementAttribute("WebFilter", typeof(WebFilter))]
    [System.Xml.Serialization.XmlElementAttribute("WebVirtualDir", typeof(WebVirtualDir))]
    public object[] Items {
      get {
        return this.itemsField;
      }
      set {
        this.itemsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType AutoStart {
      get {
        return this.autoStartField;
      }
      set {
        this.autoStartField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AutoStartSpecified {
      get {
        return this.autoStartFieldSpecified;
      }
      set {
        this.autoStartFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ConfigureIfExists {
      get {
        return this.configureIfExistsField;
      }
      set {
        this.configureIfExistsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ConfigureIfExistsSpecified {
      get {
        return this.configureIfExistsFieldSpecified;
      }
      set {
        this.configureIfExistsFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
    public string ConnectionTimeout {
      get {
        return this.connectionTimeoutField;
      }
      set {
        this.connectionTimeoutField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
      get {
        return this.descriptionField;
      }
      set {
        this.descriptionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Directory {
      get {
        return this.directoryField;
      }
      set {
        this.directoryField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DirProperties {
      get {
        return this.dirPropertiesField;
      }
      set {
        this.dirPropertiesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string Sequence {
      get {
        return this.sequenceField;
      }
      set {
        this.sequenceField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SiteId {
      get {
        return this.siteIdField;
      }
      set {
        this.siteIdField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType StartOnInstall {
      get {
        return this.startOnInstallField;
      }
      set {
        this.startOnInstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StartOnInstallSpecified {
      get {
        return this.startOnInstallFieldSpecified;
      }
      set {
        this.startOnInstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string WebApplication {
      get {
        return this.webApplicationField;
      }
      set {
        this.webApplicationField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string WebLog {
      get {
        return this.webLogField;
      }
      set {
        this.webLogField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension", IsNullable = false)]
  public partial class WebLog {

    private string idField;

    private WebLogType typeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public WebLogType Type {
      get {
        return this.typeField;
      }
      set {
        this.typeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  public enum WebLogType {

    /// <remarks/>
    IIS,

    /// <remarks/>
    NCSA,

    /// <remarks/>
    none,

    /// <remarks/>
    ODBC,

    /// <remarks/>
    W3C,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/IIsExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/IIsExtension", IsNullable = false)]
  public partial class WebServiceExtension {

    private string idField;

    private string fileField;

    private string descriptionField;

    private string groupField;

    private YesNoType allowField;

    private YesNoType uIDeletableField;

    private bool uIDeletableFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string File {
      get {
        return this.fileField;
      }
      set {
        this.fileField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
      get {
        return this.descriptionField;
      }
      set {
        this.descriptionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Group {
      get {
        return this.groupField;
      }
      set {
        this.groupField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Allow {
      get {
        return this.allowField;
      }
      set {
        this.allowField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType UIDeletable {
      get {
        return this.uIDeletableField;
      }
      set {
        this.uIDeletableField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIDeletableSpecified {
      get {
        return this.uIDeletableFieldSpecified;
      }
      set {
        this.uIDeletableFieldSpecified = value;
      }
    }
  }
}