//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Wix3.Msmq {

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/MsmqExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/MsmqExtension", IsNullable = false)]
  public partial class MessageQueue {

    private MessageQueuePermission[] messageQueuePermissionField;

    private string idField;

    private YesNoType authenticateField;

    private bool authenticateFieldSpecified;

    private string basePriorityField;

    private YesNoType journalField;

    private bool journalFieldSpecified;

    private string journalQuotaField;

    private string labelField;

    private string multicastAddressField;

    private string pathNameField;

    private MessageQueuePrivLevel privLevelField;

    private bool privLevelFieldSpecified;

    private string quotaField;

    private YesNoType transactionalField;

    private bool transactionalFieldSpecified;

    private string serviceTypeGuidField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MessageQueuePermission")]
    public MessageQueuePermission[] MessageQueuePermission {
      get {
        return this.messageQueuePermissionField;
      }
      set {
        this.messageQueuePermissionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Authenticate {
      get {
        return this.authenticateField;
      }
      set {
        this.authenticateField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AuthenticateSpecified {
      get {
        return this.authenticateFieldSpecified;
      }
      set {
        this.authenticateFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string BasePriority {
      get {
        return this.basePriorityField;
      }
      set {
        this.basePriorityField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Journal {
      get {
        return this.journalField;
      }
      set {
        this.journalField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool JournalSpecified {
      get {
        return this.journalFieldSpecified;
      }
      set {
        this.journalFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string JournalQuota {
      get {
        return this.journalQuotaField;
      }
      set {
        this.journalQuotaField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Label {
      get {
        return this.labelField;
      }
      set {
        this.labelField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MulticastAddress {
      get {
        return this.multicastAddressField;
      }
      set {
        this.multicastAddressField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PathName {
      get {
        return this.pathNameField;
      }
      set {
        this.pathNameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MessageQueuePrivLevel PrivLevel {
      get {
        return this.privLevelField;
      }
      set {
        this.privLevelField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrivLevelSpecified {
      get {
        return this.privLevelFieldSpecified;
      }
      set {
        this.privLevelFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string Quota {
      get {
        return this.quotaField;
      }
      set {
        this.quotaField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Transactional {
      get {
        return this.transactionalField;
      }
      set {
        this.transactionalField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TransactionalSpecified {
      get {
        return this.transactionalFieldSpecified;
      }
      set {
        this.transactionalFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ServiceTypeGuid {
      get {
        return this.serviceTypeGuidField;
      }
      set {
        this.serviceTypeGuidField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/MsmqExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/MsmqExtension", IsNullable = false)]
  public partial class MessageQueuePermission {

    private string idField;

    private string messageQueueField;

    private string userField;

    private string groupField;

    private YesNoType deleteMessageField;

    private bool deleteMessageFieldSpecified;

    private YesNoType peekMessageField;

    private bool peekMessageFieldSpecified;

    private YesNoType writeMessageField;

    private bool writeMessageFieldSpecified;

    private YesNoType deleteJournalMessageField;

    private bool deleteJournalMessageFieldSpecified;

    private YesNoType setQueuePropertiesField;

    private bool setQueuePropertiesFieldSpecified;

    private YesNoType getQueuePropertiesField;

    private bool getQueuePropertiesFieldSpecified;

    private YesNoType deleteQueueField;

    private bool deleteQueueFieldSpecified;

    private YesNoType getQueuePermissionsField;

    private bool getQueuePermissionsFieldSpecified;

    private YesNoType changeQueuePermissionsField;

    private bool changeQueuePermissionsFieldSpecified;

    private YesNoType takeQueueOwnershipField;

    private bool takeQueueOwnershipFieldSpecified;

    private YesNoType receiveMessageField;

    private bool receiveMessageFieldSpecified;

    private YesNoType receiveJournalMessageField;

    private bool receiveJournalMessageFieldSpecified;

    private YesNoType queueGenericReadField;

    private bool queueGenericReadFieldSpecified;

    private YesNoType queueGenericWriteField;

    private bool queueGenericWriteFieldSpecified;

    private YesNoType queueGenericExecuteField;

    private bool queueGenericExecuteFieldSpecified;

    private YesNoType queueGenericAllField;

    private bool queueGenericAllFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MessageQueue {
      get {
        return this.messageQueueField;
      }
      set {
        this.messageQueueField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string User {
      get {
        return this.userField;
      }
      set {
        this.userField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Group {
      get {
        return this.groupField;
      }
      set {
        this.groupField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType DeleteMessage {
      get {
        return this.deleteMessageField;
      }
      set {
        this.deleteMessageField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeleteMessageSpecified {
      get {
        return this.deleteMessageFieldSpecified;
      }
      set {
        this.deleteMessageFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType PeekMessage {
      get {
        return this.peekMessageField;
      }
      set {
        this.peekMessageField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PeekMessageSpecified {
      get {
        return this.peekMessageFieldSpecified;
      }
      set {
        this.peekMessageFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType WriteMessage {
      get {
        return this.writeMessageField;
      }
      set {
        this.writeMessageField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WriteMessageSpecified {
      get {
        return this.writeMessageFieldSpecified;
      }
      set {
        this.writeMessageFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType DeleteJournalMessage {
      get {
        return this.deleteJournalMessageField;
      }
      set {
        this.deleteJournalMessageField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeleteJournalMessageSpecified {
      get {
        return this.deleteJournalMessageFieldSpecified;
      }
      set {
        this.deleteJournalMessageFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType SetQueueProperties {
      get {
        return this.setQueuePropertiesField;
      }
      set {
        this.setQueuePropertiesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SetQueuePropertiesSpecified {
      get {
        return this.setQueuePropertiesFieldSpecified;
      }
      set {
        this.setQueuePropertiesFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType GetQueueProperties {
      get {
        return this.getQueuePropertiesField;
      }
      set {
        this.getQueuePropertiesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GetQueuePropertiesSpecified {
      get {
        return this.getQueuePropertiesFieldSpecified;
      }
      set {
        this.getQueuePropertiesFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType DeleteQueue {
      get {
        return this.deleteQueueField;
      }
      set {
        this.deleteQueueField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeleteQueueSpecified {
      get {
        return this.deleteQueueFieldSpecified;
      }
      set {
        this.deleteQueueFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType GetQueuePermissions {
      get {
        return this.getQueuePermissionsField;
      }
      set {
        this.getQueuePermissionsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GetQueuePermissionsSpecified {
      get {
        return this.getQueuePermissionsFieldSpecified;
      }
      set {
        this.getQueuePermissionsFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ChangeQueuePermissions {
      get {
        return this.changeQueuePermissionsField;
      }
      set {
        this.changeQueuePermissionsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ChangeQueuePermissionsSpecified {
      get {
        return this.changeQueuePermissionsFieldSpecified;
      }
      set {
        this.changeQueuePermissionsFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType TakeQueueOwnership {
      get {
        return this.takeQueueOwnershipField;
      }
      set {
        this.takeQueueOwnershipField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TakeQueueOwnershipSpecified {
      get {
        return this.takeQueueOwnershipFieldSpecified;
      }
      set {
        this.takeQueueOwnershipFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ReceiveMessage {
      get {
        return this.receiveMessageField;
      }
      set {
        this.receiveMessageField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReceiveMessageSpecified {
      get {
        return this.receiveMessageFieldSpecified;
      }
      set {
        this.receiveMessageFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ReceiveJournalMessage {
      get {
        return this.receiveJournalMessageField;
      }
      set {
        this.receiveJournalMessageField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReceiveJournalMessageSpecified {
      get {
        return this.receiveJournalMessageFieldSpecified;
      }
      set {
        this.receiveJournalMessageFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType QueueGenericRead {
      get {
        return this.queueGenericReadField;
      }
      set {
        this.queueGenericReadField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool QueueGenericReadSpecified {
      get {
        return this.queueGenericReadFieldSpecified;
      }
      set {
        this.queueGenericReadFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType QueueGenericWrite {
      get {
        return this.queueGenericWriteField;
      }
      set {
        this.queueGenericWriteField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool QueueGenericWriteSpecified {
      get {
        return this.queueGenericWriteFieldSpecified;
      }
      set {
        this.queueGenericWriteFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType QueueGenericExecute {
      get {
        return this.queueGenericExecuteField;
      }
      set {
        this.queueGenericExecuteField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool QueueGenericExecuteSpecified {
      get {
        return this.queueGenericExecuteFieldSpecified;
      }
      set {
        this.queueGenericExecuteFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType QueueGenericAll {
      get {
        return this.queueGenericAllField;
      }
      set {
        this.queueGenericAllField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool QueueGenericAllSpecified {
      get {
        return this.queueGenericAllFieldSpecified;
      }
      set {
        this.queueGenericAllFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/wix/MsmqExtension")]
  public enum YesNoType {

    /// <remarks/>
    no,

    /// <remarks/>
    yes,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/MsmqExtension")]
  public enum MessageQueuePrivLevel {

    /// <remarks/>
    none,

    /// <remarks/>
    optional,

    /// <remarks/>
    body,
  }
}