//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Wix3.Sql {

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/SqlExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/SqlExtension", IsNullable = false)]
  public partial class SqlDatabase {

    private object[] itemsField;

    private string idField;

    private string serverField;

    private string instanceField;

    private string databaseField;

    private string userField;

    private YesNoType createOnInstallField;

    private bool createOnInstallFieldSpecified;

    private YesNoType createOnReinstallField;

    private bool createOnReinstallFieldSpecified;

    private YesNoType createOnUninstallField;

    private bool createOnUninstallFieldSpecified;

    private YesNoType dropOnInstallField;

    private bool dropOnInstallFieldSpecified;

    private YesNoType dropOnReinstallField;

    private bool dropOnReinstallFieldSpecified;

    private YesNoType dropOnUninstallField;

    private bool dropOnUninstallFieldSpecified;

    private YesNoType continueOnErrorField;

    private bool continueOnErrorFieldSpecified;

    private YesNoType confirmOverwriteField;

    private bool confirmOverwriteFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SqlFileSpec", typeof(SqlFileSpec))]
    [System.Xml.Serialization.XmlElementAttribute("SqlLogFileSpec", typeof(SqlLogFileSpec))]
    [System.Xml.Serialization.XmlElementAttribute("SqlScript", typeof(SqlScript))]
    [System.Xml.Serialization.XmlElementAttribute("SqlString", typeof(SqlString))]
    public object[] Items {
      get {
        return this.itemsField;
      }
      set {
        this.itemsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Server {
      get {
        return this.serverField;
      }
      set {
        this.serverField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Instance {
      get {
        return this.instanceField;
      }
      set {
        this.instanceField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Database {
      get {
        return this.databaseField;
      }
      set {
        this.databaseField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string User {
      get {
        return this.userField;
      }
      set {
        this.userField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType CreateOnInstall {
      get {
        return this.createOnInstallField;
      }
      set {
        this.createOnInstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateOnInstallSpecified {
      get {
        return this.createOnInstallFieldSpecified;
      }
      set {
        this.createOnInstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType CreateOnReinstall {
      get {
        return this.createOnReinstallField;
      }
      set {
        this.createOnReinstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateOnReinstallSpecified {
      get {
        return this.createOnReinstallFieldSpecified;
      }
      set {
        this.createOnReinstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType CreateOnUninstall {
      get {
        return this.createOnUninstallField;
      }
      set {
        this.createOnUninstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateOnUninstallSpecified {
      get {
        return this.createOnUninstallFieldSpecified;
      }
      set {
        this.createOnUninstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType DropOnInstall {
      get {
        return this.dropOnInstallField;
      }
      set {
        this.dropOnInstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DropOnInstallSpecified {
      get {
        return this.dropOnInstallFieldSpecified;
      }
      set {
        this.dropOnInstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType DropOnReinstall {
      get {
        return this.dropOnReinstallField;
      }
      set {
        this.dropOnReinstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DropOnReinstallSpecified {
      get {
        return this.dropOnReinstallFieldSpecified;
      }
      set {
        this.dropOnReinstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType DropOnUninstall {
      get {
        return this.dropOnUninstallField;
      }
      set {
        this.dropOnUninstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DropOnUninstallSpecified {
      get {
        return this.dropOnUninstallFieldSpecified;
      }
      set {
        this.dropOnUninstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ContinueOnError {
      get {
        return this.continueOnErrorField;
      }
      set {
        this.continueOnErrorField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ContinueOnErrorSpecified {
      get {
        return this.continueOnErrorFieldSpecified;
      }
      set {
        this.continueOnErrorFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ConfirmOverwrite {
      get {
        return this.confirmOverwriteField;
      }
      set {
        this.confirmOverwriteField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ConfirmOverwriteSpecified {
      get {
        return this.confirmOverwriteFieldSpecified;
      }
      set {
        this.confirmOverwriteFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/SqlExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/SqlExtension", IsNullable = false)]
  public partial class SqlFileSpec {

    private string idField;

    private string nameField;

    private string filenameField;

    private string sizeField;

    private string maxSizeField;

    private string growthSizeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Filename {
      get {
        return this.filenameField;
      }
      set {
        this.filenameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Size {
      get {
        return this.sizeField;
      }
      set {
        this.sizeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MaxSize {
      get {
        return this.maxSizeField;
      }
      set {
        this.maxSizeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string GrowthSize {
      get {
        return this.growthSizeField;
      }
      set {
        this.growthSizeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/SqlExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/SqlExtension", IsNullable = false)]
  public partial class SqlLogFileSpec {

    private string idField;

    private string nameField;

    private string filenameField;

    private string sizeField;

    private string maxSizeField;

    private string growthSizeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Filename {
      get {
        return this.filenameField;
      }
      set {
        this.filenameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Size {
      get {
        return this.sizeField;
      }
      set {
        this.sizeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MaxSize {
      get {
        return this.maxSizeField;
      }
      set {
        this.maxSizeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string GrowthSize {
      get {
        return this.growthSizeField;
      }
      set {
        this.growthSizeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/SqlExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/SqlExtension", IsNullable = false)]
  public partial class SqlScript {

    private string idField;

    private string sqlDbField;

    private string userField;

    private string binaryKeyField;

    private YesNoType executeOnInstallField;

    private bool executeOnInstallFieldSpecified;

    private YesNoType executeOnReinstallField;

    private bool executeOnReinstallFieldSpecified;

    private YesNoType executeOnUninstallField;

    private bool executeOnUninstallFieldSpecified;

    private YesNoType rollbackOnInstallField;

    private bool rollbackOnInstallFieldSpecified;

    private YesNoType rollbackOnReinstallField;

    private bool rollbackOnReinstallFieldSpecified;

    private YesNoType rollbackOnUninstallField;

    private bool rollbackOnUninstallFieldSpecified;

    private YesNoType continueOnErrorField;

    private bool continueOnErrorFieldSpecified;

    private string sequenceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SqlDb {
      get {
        return this.sqlDbField;
      }
      set {
        this.sqlDbField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string User {
      get {
        return this.userField;
      }
      set {
        this.userField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BinaryKey {
      get {
        return this.binaryKeyField;
      }
      set {
        this.binaryKeyField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ExecuteOnInstall {
      get {
        return this.executeOnInstallField;
      }
      set {
        this.executeOnInstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExecuteOnInstallSpecified {
      get {
        return this.executeOnInstallFieldSpecified;
      }
      set {
        this.executeOnInstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ExecuteOnReinstall {
      get {
        return this.executeOnReinstallField;
      }
      set {
        this.executeOnReinstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExecuteOnReinstallSpecified {
      get {
        return this.executeOnReinstallFieldSpecified;
      }
      set {
        this.executeOnReinstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ExecuteOnUninstall {
      get {
        return this.executeOnUninstallField;
      }
      set {
        this.executeOnUninstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExecuteOnUninstallSpecified {
      get {
        return this.executeOnUninstallFieldSpecified;
      }
      set {
        this.executeOnUninstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType RollbackOnInstall {
      get {
        return this.rollbackOnInstallField;
      }
      set {
        this.rollbackOnInstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RollbackOnInstallSpecified {
      get {
        return this.rollbackOnInstallFieldSpecified;
      }
      set {
        this.rollbackOnInstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType RollbackOnReinstall {
      get {
        return this.rollbackOnReinstallField;
      }
      set {
        this.rollbackOnReinstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RollbackOnReinstallSpecified {
      get {
        return this.rollbackOnReinstallFieldSpecified;
      }
      set {
        this.rollbackOnReinstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType RollbackOnUninstall {
      get {
        return this.rollbackOnUninstallField;
      }
      set {
        this.rollbackOnUninstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RollbackOnUninstallSpecified {
      get {
        return this.rollbackOnUninstallFieldSpecified;
      }
      set {
        this.rollbackOnUninstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ContinueOnError {
      get {
        return this.continueOnErrorField;
      }
      set {
        this.continueOnErrorField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ContinueOnErrorSpecified {
      get {
        return this.continueOnErrorFieldSpecified;
      }
      set {
        this.continueOnErrorFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string Sequence {
      get {
        return this.sequenceField;
      }
      set {
        this.sequenceField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/wix/SqlExtension")]
  public enum YesNoType {

    /// <remarks/>
    no,

    /// <remarks/>
    yes,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/SqlExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/SqlExtension", IsNullable = false)]
  public partial class SqlString {

    private string idField;

    private string sQLField;

    private string userField;

    private string sqlDbField;

    private YesNoType executeOnInstallField;

    private bool executeOnInstallFieldSpecified;

    private YesNoType executeOnReinstallField;

    private bool executeOnReinstallFieldSpecified;

    private YesNoType executeOnUninstallField;

    private bool executeOnUninstallFieldSpecified;

    private YesNoType rollbackOnInstallField;

    private bool rollbackOnInstallFieldSpecified;

    private YesNoType rollbackOnReinstallField;

    private bool rollbackOnReinstallFieldSpecified;

    private YesNoType rollbackOnUninstallField;

    private bool rollbackOnUninstallFieldSpecified;

    private YesNoType continueOnErrorField;

    private bool continueOnErrorFieldSpecified;

    private string sequenceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SQL {
      get {
        return this.sQLField;
      }
      set {
        this.sQLField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string User {
      get {
        return this.userField;
      }
      set {
        this.userField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SqlDb {
      get {
        return this.sqlDbField;
      }
      set {
        this.sqlDbField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ExecuteOnInstall {
      get {
        return this.executeOnInstallField;
      }
      set {
        this.executeOnInstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExecuteOnInstallSpecified {
      get {
        return this.executeOnInstallFieldSpecified;
      }
      set {
        this.executeOnInstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ExecuteOnReinstall {
      get {
        return this.executeOnReinstallField;
      }
      set {
        this.executeOnReinstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExecuteOnReinstallSpecified {
      get {
        return this.executeOnReinstallFieldSpecified;
      }
      set {
        this.executeOnReinstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ExecuteOnUninstall {
      get {
        return this.executeOnUninstallField;
      }
      set {
        this.executeOnUninstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExecuteOnUninstallSpecified {
      get {
        return this.executeOnUninstallFieldSpecified;
      }
      set {
        this.executeOnUninstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType RollbackOnInstall {
      get {
        return this.rollbackOnInstallField;
      }
      set {
        this.rollbackOnInstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RollbackOnInstallSpecified {
      get {
        return this.rollbackOnInstallFieldSpecified;
      }
      set {
        this.rollbackOnInstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType RollbackOnReinstall {
      get {
        return this.rollbackOnReinstallField;
      }
      set {
        this.rollbackOnReinstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RollbackOnReinstallSpecified {
      get {
        return this.rollbackOnReinstallFieldSpecified;
      }
      set {
        this.rollbackOnReinstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType RollbackOnUninstall {
      get {
        return this.rollbackOnUninstallField;
      }
      set {
        this.rollbackOnUninstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RollbackOnUninstallSpecified {
      get {
        return this.rollbackOnUninstallFieldSpecified;
      }
      set {
        this.rollbackOnUninstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ContinueOnError {
      get {
        return this.continueOnErrorField;
      }
      set {
        this.continueOnErrorField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ContinueOnErrorSpecified {
      get {
        return this.continueOnErrorFieldSpecified;
      }
      set {
        this.continueOnErrorFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string Sequence {
      get {
        return this.sequenceField;
      }
      set {
        this.sequenceField = value;
      }
    }
  }
}