//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Wix3.Util {

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension", IsNullable = false)]
  public partial class CloseApplication {

    private string idField;

    private string targetField;

    private string descriptionField;

    private string sequenceField;

    private YesNoType closeMessageField;

    private bool closeMessageFieldSpecified;

    private YesNoType elevatedCloseMessageField;

    private bool elevatedCloseMessageFieldSpecified;

    private YesNoType rebootPromptField;

    private bool rebootPromptFieldSpecified;

    private string propertyField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Target {
      get {
        return this.targetField;
      }
      set {
        this.targetField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
      get {
        return this.descriptionField;
      }
      set {
        this.descriptionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string Sequence {
      get {
        return this.sequenceField;
      }
      set {
        this.sequenceField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType CloseMessage {
      get {
        return this.closeMessageField;
      }
      set {
        this.closeMessageField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CloseMessageSpecified {
      get {
        return this.closeMessageFieldSpecified;
      }
      set {
        this.closeMessageFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ElevatedCloseMessage {
      get {
        return this.elevatedCloseMessageField;
      }
      set {
        this.elevatedCloseMessageField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ElevatedCloseMessageSpecified {
      get {
        return this.elevatedCloseMessageFieldSpecified;
      }
      set {
        this.elevatedCloseMessageFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType RebootPrompt {
      get {
        return this.rebootPromptField;
      }
      set {
        this.rebootPromptField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RebootPromptSpecified {
      get {
        return this.rebootPromptFieldSpecified;
      }
      set {
        this.rebootPromptFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Property {
      get {
        return this.propertyField;
      }
      set {
        this.propertyField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
      get {
        return this.valueField;
      }
      set {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  public enum YesNoType {

    /// <remarks/>
    no,

    /// <remarks/>
    yes,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension", IsNullable = false)]
  public partial class EventSource {

    private string categoryCountField;

    private string categoryMessageFileField;

    private string eventMessageFileField;

    private YesNoType keyPathField;

    private bool keyPathFieldSpecified;

    private string logField;

    private string nameField;

    private string parameterMessageFileField;

    private YesNoType supportsErrorsField;

    private bool supportsErrorsFieldSpecified;

    private YesNoType supportsFailureAuditsField;

    private bool supportsFailureAuditsFieldSpecified;

    private YesNoType supportsInformationalsField;

    private bool supportsInformationalsFieldSpecified;

    private YesNoType supportsSuccessAuditsField;

    private bool supportsSuccessAuditsFieldSpecified;

    private YesNoType supportsWarningsField;

    private bool supportsWarningsFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string CategoryCount {
      get {
        return this.categoryCountField;
      }
      set {
        this.categoryCountField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CategoryMessageFile {
      get {
        return this.categoryMessageFileField;
      }
      set {
        this.categoryMessageFileField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EventMessageFile {
      get {
        return this.eventMessageFileField;
      }
      set {
        this.eventMessageFileField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType KeyPath {
      get {
        return this.keyPathField;
      }
      set {
        this.keyPathField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool KeyPathSpecified {
      get {
        return this.keyPathFieldSpecified;
      }
      set {
        this.keyPathFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Log {
      get {
        return this.logField;
      }
      set {
        this.logField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ParameterMessageFile {
      get {
        return this.parameterMessageFileField;
      }
      set {
        this.parameterMessageFileField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType SupportsErrors {
      get {
        return this.supportsErrorsField;
      }
      set {
        this.supportsErrorsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SupportsErrorsSpecified {
      get {
        return this.supportsErrorsFieldSpecified;
      }
      set {
        this.supportsErrorsFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType SupportsFailureAudits {
      get {
        return this.supportsFailureAuditsField;
      }
      set {
        this.supportsFailureAuditsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SupportsFailureAuditsSpecified {
      get {
        return this.supportsFailureAuditsFieldSpecified;
      }
      set {
        this.supportsFailureAuditsFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType SupportsInformationals {
      get {
        return this.supportsInformationalsField;
      }
      set {
        this.supportsInformationalsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SupportsInformationalsSpecified {
      get {
        return this.supportsInformationalsFieldSpecified;
      }
      set {
        this.supportsInformationalsFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType SupportsSuccessAudits {
      get {
        return this.supportsSuccessAuditsField;
      }
      set {
        this.supportsSuccessAuditsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SupportsSuccessAuditsSpecified {
      get {
        return this.supportsSuccessAuditsFieldSpecified;
      }
      set {
        this.supportsSuccessAuditsFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType SupportsWarnings {
      get {
        return this.supportsWarningsField;
      }
      set {
        this.supportsWarningsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SupportsWarningsSpecified {
      get {
        return this.supportsWarningsFieldSpecified;
      }
      set {
        this.supportsWarningsFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension", IsNullable = false)]
  public partial class FileShare {

    private FileSharePermission[] fileSharePermissionField;

    private string idField;

    private string nameField;

    private string descriptionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FileSharePermission")]
    public FileSharePermission[] FileSharePermission {
      get {
        return this.fileSharePermissionField;
      }
      set {
        this.fileSharePermissionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
      get {
        return this.descriptionField;
      }
      set {
        this.descriptionField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension", IsNullable = false)]
  public partial class FileSharePermission {

    private string userField;

    private YesNoType readField;

    private bool readFieldSpecified;

    private YesNoType deleteField;

    private bool deleteFieldSpecified;

    private YesNoType readPermissionField;

    private bool readPermissionFieldSpecified;

    private YesNoType changePermissionField;

    private bool changePermissionFieldSpecified;

    private YesNoType takeOwnershipField;

    private bool takeOwnershipFieldSpecified;

    private YesNoType readAttributesField;

    private bool readAttributesFieldSpecified;

    private YesNoType writeAttributesField;

    private bool writeAttributesFieldSpecified;

    private YesNoType readExtendedAttributesField;

    private bool readExtendedAttributesFieldSpecified;

    private YesNoType writeExtendedAttributesField;

    private bool writeExtendedAttributesFieldSpecified;

    private YesNoType synchronizeField;

    private bool synchronizeFieldSpecified;

    private YesNoType createFileField;

    private bool createFileFieldSpecified;

    private YesNoType createChildField;

    private bool createChildFieldSpecified;

    private YesNoType deleteChildField;

    private bool deleteChildFieldSpecified;

    private YesNoType traverseField;

    private bool traverseFieldSpecified;

    private YesNoType genericAllField;

    private bool genericAllFieldSpecified;

    private YesNoType genericExecuteField;

    private bool genericExecuteFieldSpecified;

    private YesNoType genericWriteField;

    private bool genericWriteFieldSpecified;

    private YesNoType genericReadField;

    private bool genericReadFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string User {
      get {
        return this.userField;
      }
      set {
        this.userField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Read {
      get {
        return this.readField;
      }
      set {
        this.readField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReadSpecified {
      get {
        return this.readFieldSpecified;
      }
      set {
        this.readFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Delete {
      get {
        return this.deleteField;
      }
      set {
        this.deleteField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeleteSpecified {
      get {
        return this.deleteFieldSpecified;
      }
      set {
        this.deleteFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ReadPermission {
      get {
        return this.readPermissionField;
      }
      set {
        this.readPermissionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReadPermissionSpecified {
      get {
        return this.readPermissionFieldSpecified;
      }
      set {
        this.readPermissionFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ChangePermission {
      get {
        return this.changePermissionField;
      }
      set {
        this.changePermissionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ChangePermissionSpecified {
      get {
        return this.changePermissionFieldSpecified;
      }
      set {
        this.changePermissionFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType TakeOwnership {
      get {
        return this.takeOwnershipField;
      }
      set {
        this.takeOwnershipField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TakeOwnershipSpecified {
      get {
        return this.takeOwnershipFieldSpecified;
      }
      set {
        this.takeOwnershipFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ReadAttributes {
      get {
        return this.readAttributesField;
      }
      set {
        this.readAttributesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReadAttributesSpecified {
      get {
        return this.readAttributesFieldSpecified;
      }
      set {
        this.readAttributesFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType WriteAttributes {
      get {
        return this.writeAttributesField;
      }
      set {
        this.writeAttributesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WriteAttributesSpecified {
      get {
        return this.writeAttributesFieldSpecified;
      }
      set {
        this.writeAttributesFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ReadExtendedAttributes {
      get {
        return this.readExtendedAttributesField;
      }
      set {
        this.readExtendedAttributesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReadExtendedAttributesSpecified {
      get {
        return this.readExtendedAttributesFieldSpecified;
      }
      set {
        this.readExtendedAttributesFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType WriteExtendedAttributes {
      get {
        return this.writeExtendedAttributesField;
      }
      set {
        this.writeExtendedAttributesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WriteExtendedAttributesSpecified {
      get {
        return this.writeExtendedAttributesFieldSpecified;
      }
      set {
        this.writeExtendedAttributesFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Synchronize {
      get {
        return this.synchronizeField;
      }
      set {
        this.synchronizeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SynchronizeSpecified {
      get {
        return this.synchronizeFieldSpecified;
      }
      set {
        this.synchronizeFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType CreateFile {
      get {
        return this.createFileField;
      }
      set {
        this.createFileField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateFileSpecified {
      get {
        return this.createFileFieldSpecified;
      }
      set {
        this.createFileFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType CreateChild {
      get {
        return this.createChildField;
      }
      set {
        this.createChildField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateChildSpecified {
      get {
        return this.createChildFieldSpecified;
      }
      set {
        this.createChildFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType DeleteChild {
      get {
        return this.deleteChildField;
      }
      set {
        this.deleteChildField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeleteChildSpecified {
      get {
        return this.deleteChildFieldSpecified;
      }
      set {
        this.deleteChildFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Traverse {
      get {
        return this.traverseField;
      }
      set {
        this.traverseField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TraverseSpecified {
      get {
        return this.traverseFieldSpecified;
      }
      set {
        this.traverseFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType GenericAll {
      get {
        return this.genericAllField;
      }
      set {
        this.genericAllField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GenericAllSpecified {
      get {
        return this.genericAllFieldSpecified;
      }
      set {
        this.genericAllFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType GenericExecute {
      get {
        return this.genericExecuteField;
      }
      set {
        this.genericExecuteField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GenericExecuteSpecified {
      get {
        return this.genericExecuteFieldSpecified;
      }
      set {
        this.genericExecuteFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType GenericWrite {
      get {
        return this.genericWriteField;
      }
      set {
        this.genericWriteField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GenericWriteSpecified {
      get {
        return this.genericWriteFieldSpecified;
      }
      set {
        this.genericWriteFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType GenericRead {
      get {
        return this.genericReadField;
      }
      set {
        this.genericReadField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GenericReadSpecified {
      get {
        return this.genericReadFieldSpecified;
      }
      set {
        this.genericReadFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension", IsNullable = false)]
  public partial class Group {

    private string idField;

    private string nameField;

    private string domainField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Domain {
      get {
        return this.domainField;
      }
      set {
        this.domainField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension", IsNullable = false)]
  public partial class GroupRef {

    private string idField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension", IsNullable = false)]
  public partial class InternetShortcut {

    private string idField;

    private string directoryField;

    private string nameField;

    private string targetField;

    private InternetShortcutType typeField;

    private bool typeFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Directory {
      get {
        return this.directoryField;
      }
      set {
        this.directoryField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Target {
      get {
        return this.targetField;
      }
      set {
        this.targetField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public InternetShortcutType Type {
      get {
        return this.typeField;
      }
      set {
        this.typeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TypeSpecified {
      get {
        return this.typeFieldSpecified;
      }
      set {
        this.typeFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  public enum InternetShortcutType {

    /// <remarks/>
    url,

    /// <remarks/>
    link,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension", IsNullable = false)]
  public partial class PerformanceCategory {

    private PerformanceCounter[] performanceCounterField;

    private string idField;

    private string nameField;

    private string helpField;

    private YesNoType multiInstanceField;

    private bool multiInstanceFieldSpecified;

    private string libraryField;

    private string openField;

    private string closeField;

    private string collectField;

    private PerformanceCounterLanguageType defaultLanguageField;

    private bool defaultLanguageFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PerformanceCounter")]
    public PerformanceCounter[] PerformanceCounter {
      get {
        return this.performanceCounterField;
      }
      set {
        this.performanceCounterField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Help {
      get {
        return this.helpField;
      }
      set {
        this.helpField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType MultiInstance {
      get {
        return this.multiInstanceField;
      }
      set {
        this.multiInstanceField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MultiInstanceSpecified {
      get {
        return this.multiInstanceFieldSpecified;
      }
      set {
        this.multiInstanceFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Library {
      get {
        return this.libraryField;
      }
      set {
        this.libraryField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Open {
      get {
        return this.openField;
      }
      set {
        this.openField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Close {
      get {
        return this.closeField;
      }
      set {
        this.closeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Collect {
      get {
        return this.collectField;
      }
      set {
        this.collectField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PerformanceCounterLanguageType DefaultLanguage {
      get {
        return this.defaultLanguageField;
      }
      set {
        this.defaultLanguageField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DefaultLanguageSpecified {
      get {
        return this.defaultLanguageFieldSpecified;
      }
      set {
        this.defaultLanguageFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension", IsNullable = false)]
  public partial class PerformanceCounter {

    private string nameField;

    private string helpField;

    private PerformanceCounterTypesType typeField;

    private bool typeFieldSpecified;

    private PerformanceCounterLanguageType languageField;

    private bool languageFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Help {
      get {
        return this.helpField;
      }
      set {
        this.helpField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PerformanceCounterTypesType Type {
      get {
        return this.typeField;
      }
      set {
        this.typeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TypeSpecified {
      get {
        return this.typeFieldSpecified;
      }
      set {
        this.typeFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PerformanceCounterLanguageType Language {
      get {
        return this.languageField;
      }
      set {
        this.languageField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LanguageSpecified {
      get {
        return this.languageFieldSpecified;
      }
      set {
        this.languageFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  public enum PerformanceCounterTypesType {

    /// <remarks/>
    averageBase,

    /// <remarks/>
    averageCount64,

    /// <remarks/>
    averageTimer32,

    /// <remarks/>
    counterDelta32,

    /// <remarks/>
    counterTimerInverse,

    /// <remarks/>
    sampleFraction,

    /// <remarks/>
    timer100Ns,

    /// <remarks/>
    counterTimer,

    /// <remarks/>
    rawFraction,

    /// <remarks/>
    timer100NsInverse,

    /// <remarks/>
    counterMultiTimer,

    /// <remarks/>
    counterMultiTimer100Ns,

    /// <remarks/>
    counterMultiTimerInverse,

    /// <remarks/>
    counterMultiTimer100NsInverse,

    /// <remarks/>
    elapsedTime,

    /// <remarks/>
    sampleBase,

    /// <remarks/>
    rawBase,

    /// <remarks/>
    counterMultiBase,

    /// <remarks/>
    rateOfCountsPerSecond64,

    /// <remarks/>
    rateOfCountsPerSecond32,

    /// <remarks/>
    countPerTimeInterval64,

    /// <remarks/>
    countPerTimeInterval32,

    /// <remarks/>
    sampleCounter,

    /// <remarks/>
    counterDelta64,

    /// <remarks/>
    numberOfItems64,

    /// <remarks/>
    numberOfItems32,

    /// <remarks/>
    numberOfItemsHEX64,

    /// <remarks/>
    numberOfItemsHEX32,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  public enum PerformanceCounterLanguageType {

    /// <remarks/>
    afrikaans,

    /// <remarks/>
    albanian,

    /// <remarks/>
    arabic,

    /// <remarks/>
    armenian,

    /// <remarks/>
    assamese,

    /// <remarks/>
    azeri,

    /// <remarks/>
    basque,

    /// <remarks/>
    belarusian,

    /// <remarks/>
    bengali,

    /// <remarks/>
    bulgarian,

    /// <remarks/>
    catalan,

    /// <remarks/>
    chinese,

    /// <remarks/>
    croatian,

    /// <remarks/>
    czech,

    /// <remarks/>
    danish,

    /// <remarks/>
    divehi,

    /// <remarks/>
    dutch,

    /// <remarks/>
    english,

    /// <remarks/>
    estonian,

    /// <remarks/>
    faeroese,

    /// <remarks/>
    farsi,

    /// <remarks/>
    finnish,

    /// <remarks/>
    french,

    /// <remarks/>
    galician,

    /// <remarks/>
    georgian,

    /// <remarks/>
    german,

    /// <remarks/>
    greek,

    /// <remarks/>
    gujarati,

    /// <remarks/>
    hebrew,

    /// <remarks/>
    hindi,

    /// <remarks/>
    hungarian,

    /// <remarks/>
    icelandic,

    /// <remarks/>
    indonesian,

    /// <remarks/>
    italian,

    /// <remarks/>
    japanese,

    /// <remarks/>
    kannada,

    /// <remarks/>
    kashmiri,

    /// <remarks/>
    kazak,

    /// <remarks/>
    konkani,

    /// <remarks/>
    korean,

    /// <remarks/>
    kyrgyz,

    /// <remarks/>
    latvian,

    /// <remarks/>
    lithuanian,

    /// <remarks/>
    macedonian,

    /// <remarks/>
    malay,

    /// <remarks/>
    malayalam,

    /// <remarks/>
    manipuri,

    /// <remarks/>
    marathi,

    /// <remarks/>
    mongolian,

    /// <remarks/>
    nepali,

    /// <remarks/>
    norwegian,

    /// <remarks/>
    oriya,

    /// <remarks/>
    polish,

    /// <remarks/>
    portuguese,

    /// <remarks/>
    punjabi,

    /// <remarks/>
    romanian,

    /// <remarks/>
    russian,

    /// <remarks/>
    sanskrit,

    /// <remarks/>
    serbian,

    /// <remarks/>
    sindhi,

    /// <remarks/>
    slovak,

    /// <remarks/>
    slovenian,

    /// <remarks/>
    spanish,

    /// <remarks/>
    swahili,

    /// <remarks/>
    swedish,

    /// <remarks/>
    syriac,

    /// <remarks/>
    tamil,

    /// <remarks/>
    tatar,

    /// <remarks/>
    telugu,

    /// <remarks/>
    thai,

    /// <remarks/>
    turkish,

    /// <remarks/>
    ukrainian,

    /// <remarks/>
    urdu,

    /// <remarks/>
    uzbek,

    /// <remarks/>
    vietnamese,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension", IsNullable = false)]
  public partial class PerfCounter {

    private string nameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension", IsNullable = false)]
  public partial class PerfCounterManifest {

    private string resourceFileDirectoryField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ResourceFileDirectory {
      get {
        return this.resourceFileDirectoryField;
      }
      set {
        this.resourceFileDirectoryField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension", IsNullable = false)]
  public partial class EventManifest {

    private string messageFileField;

    private string parameterFileField;

    private string resourceFileField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MessageFile {
      get {
        return this.messageFileField;
      }
      set {
        this.messageFileField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ParameterFile {
      get {
        return this.parameterFileField;
      }
      set {
        this.parameterFileField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ResourceFile {
      get {
        return this.resourceFileField;
      }
      set {
        this.resourceFileField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension", IsNullable = false)]
  public partial class PermissionEx {

    private string domainField;

    private string userField;

    private YesNoType readField;

    private bool readFieldSpecified;

    private YesNoType deleteField;

    private bool deleteFieldSpecified;

    private YesNoType readPermissionField;

    private bool readPermissionFieldSpecified;

    private YesNoType changePermissionField;

    private bool changePermissionFieldSpecified;

    private YesNoType takeOwnershipField;

    private bool takeOwnershipFieldSpecified;

    private YesNoType readAttributesField;

    private bool readAttributesFieldSpecified;

    private YesNoType writeAttributesField;

    private bool writeAttributesFieldSpecified;

    private YesNoType readExtendedAttributesField;

    private bool readExtendedAttributesFieldSpecified;

    private YesNoType writeExtendedAttributesField;

    private bool writeExtendedAttributesFieldSpecified;

    private YesNoType synchronizeField;

    private bool synchronizeFieldSpecified;

    private YesNoType createFileField;

    private bool createFileFieldSpecified;

    private YesNoType createChildField;

    private bool createChildFieldSpecified;

    private YesNoType deleteChildField;

    private bool deleteChildFieldSpecified;

    private YesNoType traverseField;

    private bool traverseFieldSpecified;

    private YesNoType appendField;

    private bool appendFieldSpecified;

    private YesNoType executeField;

    private bool executeFieldSpecified;

    private YesNoType writeField;

    private bool writeFieldSpecified;

    private YesNoType createSubkeysField;

    private bool createSubkeysFieldSpecified;

    private YesNoType enumerateSubkeysField;

    private bool enumerateSubkeysFieldSpecified;

    private YesNoType notifyField;

    private bool notifyFieldSpecified;

    private YesNoType createLinkField;

    private bool createLinkFieldSpecified;

    private YesNoType genericAllField;

    private bool genericAllFieldSpecified;

    private YesNoType genericExecuteField;

    private bool genericExecuteFieldSpecified;

    private YesNoType genericWriteField;

    private bool genericWriteFieldSpecified;

    private YesNoType genericReadField;

    private bool genericReadFieldSpecified;

    private YesNoType serviceQueryConfigField;

    private bool serviceQueryConfigFieldSpecified;

    private YesNoType serviceChangeConfigField;

    private bool serviceChangeConfigFieldSpecified;

    private YesNoType serviceQueryStatusField;

    private bool serviceQueryStatusFieldSpecified;

    private YesNoType serviceEnumerateDependentsField;

    private bool serviceEnumerateDependentsFieldSpecified;

    private YesNoType serviceStartField;

    private bool serviceStartFieldSpecified;

    private YesNoType serviceStopField;

    private bool serviceStopFieldSpecified;

    private YesNoType servicePauseContinueField;

    private bool servicePauseContinueFieldSpecified;

    private YesNoType serviceInterrogateField;

    private bool serviceInterrogateFieldSpecified;

    private YesNoType serviceUserDefinedControlField;

    private bool serviceUserDefinedControlFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Domain {
      get {
        return this.domainField;
      }
      set {
        this.domainField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string User {
      get {
        return this.userField;
      }
      set {
        this.userField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Read {
      get {
        return this.readField;
      }
      set {
        this.readField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReadSpecified {
      get {
        return this.readFieldSpecified;
      }
      set {
        this.readFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Delete {
      get {
        return this.deleteField;
      }
      set {
        this.deleteField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeleteSpecified {
      get {
        return this.deleteFieldSpecified;
      }
      set {
        this.deleteFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ReadPermission {
      get {
        return this.readPermissionField;
      }
      set {
        this.readPermissionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReadPermissionSpecified {
      get {
        return this.readPermissionFieldSpecified;
      }
      set {
        this.readPermissionFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ChangePermission {
      get {
        return this.changePermissionField;
      }
      set {
        this.changePermissionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ChangePermissionSpecified {
      get {
        return this.changePermissionFieldSpecified;
      }
      set {
        this.changePermissionFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType TakeOwnership {
      get {
        return this.takeOwnershipField;
      }
      set {
        this.takeOwnershipField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TakeOwnershipSpecified {
      get {
        return this.takeOwnershipFieldSpecified;
      }
      set {
        this.takeOwnershipFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ReadAttributes {
      get {
        return this.readAttributesField;
      }
      set {
        this.readAttributesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReadAttributesSpecified {
      get {
        return this.readAttributesFieldSpecified;
      }
      set {
        this.readAttributesFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType WriteAttributes {
      get {
        return this.writeAttributesField;
      }
      set {
        this.writeAttributesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WriteAttributesSpecified {
      get {
        return this.writeAttributesFieldSpecified;
      }
      set {
        this.writeAttributesFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ReadExtendedAttributes {
      get {
        return this.readExtendedAttributesField;
      }
      set {
        this.readExtendedAttributesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReadExtendedAttributesSpecified {
      get {
        return this.readExtendedAttributesFieldSpecified;
      }
      set {
        this.readExtendedAttributesFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType WriteExtendedAttributes {
      get {
        return this.writeExtendedAttributesField;
      }
      set {
        this.writeExtendedAttributesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WriteExtendedAttributesSpecified {
      get {
        return this.writeExtendedAttributesFieldSpecified;
      }
      set {
        this.writeExtendedAttributesFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Synchronize {
      get {
        return this.synchronizeField;
      }
      set {
        this.synchronizeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SynchronizeSpecified {
      get {
        return this.synchronizeFieldSpecified;
      }
      set {
        this.synchronizeFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType CreateFile {
      get {
        return this.createFileField;
      }
      set {
        this.createFileField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateFileSpecified {
      get {
        return this.createFileFieldSpecified;
      }
      set {
        this.createFileFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType CreateChild {
      get {
        return this.createChildField;
      }
      set {
        this.createChildField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateChildSpecified {
      get {
        return this.createChildFieldSpecified;
      }
      set {
        this.createChildFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType DeleteChild {
      get {
        return this.deleteChildField;
      }
      set {
        this.deleteChildField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeleteChildSpecified {
      get {
        return this.deleteChildFieldSpecified;
      }
      set {
        this.deleteChildFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Traverse {
      get {
        return this.traverseField;
      }
      set {
        this.traverseField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TraverseSpecified {
      get {
        return this.traverseFieldSpecified;
      }
      set {
        this.traverseFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Append {
      get {
        return this.appendField;
      }
      set {
        this.appendField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AppendSpecified {
      get {
        return this.appendFieldSpecified;
      }
      set {
        this.appendFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Execute {
      get {
        return this.executeField;
      }
      set {
        this.executeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExecuteSpecified {
      get {
        return this.executeFieldSpecified;
      }
      set {
        this.executeFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Write {
      get {
        return this.writeField;
      }
      set {
        this.writeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WriteSpecified {
      get {
        return this.writeFieldSpecified;
      }
      set {
        this.writeFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType CreateSubkeys {
      get {
        return this.createSubkeysField;
      }
      set {
        this.createSubkeysField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateSubkeysSpecified {
      get {
        return this.createSubkeysFieldSpecified;
      }
      set {
        this.createSubkeysFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType EnumerateSubkeys {
      get {
        return this.enumerateSubkeysField;
      }
      set {
        this.enumerateSubkeysField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EnumerateSubkeysSpecified {
      get {
        return this.enumerateSubkeysFieldSpecified;
      }
      set {
        this.enumerateSubkeysFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Notify {
      get {
        return this.notifyField;
      }
      set {
        this.notifyField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NotifySpecified {
      get {
        return this.notifyFieldSpecified;
      }
      set {
        this.notifyFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType CreateLink {
      get {
        return this.createLinkField;
      }
      set {
        this.createLinkField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateLinkSpecified {
      get {
        return this.createLinkFieldSpecified;
      }
      set {
        this.createLinkFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType GenericAll {
      get {
        return this.genericAllField;
      }
      set {
        this.genericAllField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GenericAllSpecified {
      get {
        return this.genericAllFieldSpecified;
      }
      set {
        this.genericAllFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType GenericExecute {
      get {
        return this.genericExecuteField;
      }
      set {
        this.genericExecuteField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GenericExecuteSpecified {
      get {
        return this.genericExecuteFieldSpecified;
      }
      set {
        this.genericExecuteFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType GenericWrite {
      get {
        return this.genericWriteField;
      }
      set {
        this.genericWriteField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GenericWriteSpecified {
      get {
        return this.genericWriteFieldSpecified;
      }
      set {
        this.genericWriteFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType GenericRead {
      get {
        return this.genericReadField;
      }
      set {
        this.genericReadField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GenericReadSpecified {
      get {
        return this.genericReadFieldSpecified;
      }
      set {
        this.genericReadFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ServiceQueryConfig {
      get {
        return this.serviceQueryConfigField;
      }
      set {
        this.serviceQueryConfigField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ServiceQueryConfigSpecified {
      get {
        return this.serviceQueryConfigFieldSpecified;
      }
      set {
        this.serviceQueryConfigFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ServiceChangeConfig {
      get {
        return this.serviceChangeConfigField;
      }
      set {
        this.serviceChangeConfigField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ServiceChangeConfigSpecified {
      get {
        return this.serviceChangeConfigFieldSpecified;
      }
      set {
        this.serviceChangeConfigFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ServiceQueryStatus {
      get {
        return this.serviceQueryStatusField;
      }
      set {
        this.serviceQueryStatusField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ServiceQueryStatusSpecified {
      get {
        return this.serviceQueryStatusFieldSpecified;
      }
      set {
        this.serviceQueryStatusFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ServiceEnumerateDependents {
      get {
        return this.serviceEnumerateDependentsField;
      }
      set {
        this.serviceEnumerateDependentsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ServiceEnumerateDependentsSpecified {
      get {
        return this.serviceEnumerateDependentsFieldSpecified;
      }
      set {
        this.serviceEnumerateDependentsFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ServiceStart {
      get {
        return this.serviceStartField;
      }
      set {
        this.serviceStartField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ServiceStartSpecified {
      get {
        return this.serviceStartFieldSpecified;
      }
      set {
        this.serviceStartFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ServiceStop {
      get {
        return this.serviceStopField;
      }
      set {
        this.serviceStopField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ServiceStopSpecified {
      get {
        return this.serviceStopFieldSpecified;
      }
      set {
        this.serviceStopFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ServicePauseContinue {
      get {
        return this.servicePauseContinueField;
      }
      set {
        this.servicePauseContinueField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ServicePauseContinueSpecified {
      get {
        return this.servicePauseContinueFieldSpecified;
      }
      set {
        this.servicePauseContinueFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ServiceInterrogate {
      get {
        return this.serviceInterrogateField;
      }
      set {
        this.serviceInterrogateField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ServiceInterrogateSpecified {
      get {
        return this.serviceInterrogateFieldSpecified;
      }
      set {
        this.serviceInterrogateFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType ServiceUserDefinedControl {
      get {
        return this.serviceUserDefinedControlField;
      }
      set {
        this.serviceUserDefinedControlField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ServiceUserDefinedControlSpecified {
      get {
        return this.serviceUserDefinedControlFieldSpecified;
      }
      set {
        this.serviceUserDefinedControlFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension", IsNullable = false)]
  public partial class ServiceConfig {

    private string serviceNameField;

    private ServiceConfigFirstFailureActionType firstFailureActionTypeField;

    private ServiceConfigSecondFailureActionType secondFailureActionTypeField;

    private ServiceConfigThirdFailureActionType thirdFailureActionTypeField;

    private string resetPeriodInDaysField;

    private string restartServiceDelayInSecondsField;

    private string programCommandLineField;

    private string rebootMessageField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ServiceName {
      get {
        return this.serviceNameField;
      }
      set {
        this.serviceNameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ServiceConfigFirstFailureActionType FirstFailureActionType {
      get {
        return this.firstFailureActionTypeField;
      }
      set {
        this.firstFailureActionTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ServiceConfigSecondFailureActionType SecondFailureActionType {
      get {
        return this.secondFailureActionTypeField;
      }
      set {
        this.secondFailureActionTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ServiceConfigThirdFailureActionType ThirdFailureActionType {
      get {
        return this.thirdFailureActionTypeField;
      }
      set {
        this.thirdFailureActionTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string ResetPeriodInDays {
      get {
        return this.resetPeriodInDaysField;
      }
      set {
        this.resetPeriodInDaysField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string RestartServiceDelayInSeconds {
      get {
        return this.restartServiceDelayInSecondsField;
      }
      set {
        this.restartServiceDelayInSecondsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProgramCommandLine {
      get {
        return this.programCommandLineField;
      }
      set {
        this.programCommandLineField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RebootMessage {
      get {
        return this.rebootMessageField;
      }
      set {
        this.rebootMessageField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  public enum ServiceConfigFirstFailureActionType {

    /// <remarks/>
    none,

    /// <remarks/>
    reboot,

    /// <remarks/>
    restart,

    /// <remarks/>
    runCommand,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  public enum ServiceConfigSecondFailureActionType {

    /// <remarks/>
    none,

    /// <remarks/>
    reboot,

    /// <remarks/>
    restart,

    /// <remarks/>
    runCommand,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  public enum ServiceConfigThirdFailureActionType {

    /// <remarks/>
    none,

    /// <remarks/>
    reboot,

    /// <remarks/>
    restart,

    /// <remarks/>
    runCommand,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension", IsNullable = false)]
  public partial class User {

    private GroupRef[] groupRefField;

    private string idField;

    private string nameField;

    private string domainField;

    private string passwordField;

    private YesNoType passwordNeverExpiresField;

    private bool passwordNeverExpiresFieldSpecified;

    private YesNoType canNotChangePasswordField;

    private bool canNotChangePasswordFieldSpecified;

    private YesNoType removeOnUninstallField;

    private bool removeOnUninstallFieldSpecified;

    private YesNoType failIfExistsField;

    private bool failIfExistsFieldSpecified;

    private YesNoType logonAsServiceField;

    private bool logonAsServiceFieldSpecified;

    private YesNoType updateIfExistsField;

    private bool updateIfExistsFieldSpecified;

    private YesNoType passwordExpiredField;

    private bool passwordExpiredFieldSpecified;

    private YesNoType disabledField;

    private bool disabledFieldSpecified;

    private YesNoType createUserField;

    private bool createUserFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GroupRef")]
    public GroupRef[] GroupRef {
      get {
        return this.groupRefField;
      }
      set {
        this.groupRefField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Domain {
      get {
        return this.domainField;
      }
      set {
        this.domainField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Password {
      get {
        return this.passwordField;
      }
      set {
        this.passwordField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType PasswordNeverExpires {
      get {
        return this.passwordNeverExpiresField;
      }
      set {
        this.passwordNeverExpiresField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PasswordNeverExpiresSpecified {
      get {
        return this.passwordNeverExpiresFieldSpecified;
      }
      set {
        this.passwordNeverExpiresFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType CanNotChangePassword {
      get {
        return this.canNotChangePasswordField;
      }
      set {
        this.canNotChangePasswordField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CanNotChangePasswordSpecified {
      get {
        return this.canNotChangePasswordFieldSpecified;
      }
      set {
        this.canNotChangePasswordFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType RemoveOnUninstall {
      get {
        return this.removeOnUninstallField;
      }
      set {
        this.removeOnUninstallField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RemoveOnUninstallSpecified {
      get {
        return this.removeOnUninstallFieldSpecified;
      }
      set {
        this.removeOnUninstallFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType FailIfExists {
      get {
        return this.failIfExistsField;
      }
      set {
        this.failIfExistsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FailIfExistsSpecified {
      get {
        return this.failIfExistsFieldSpecified;
      }
      set {
        this.failIfExistsFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType LogonAsService {
      get {
        return this.logonAsServiceField;
      }
      set {
        this.logonAsServiceField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LogonAsServiceSpecified {
      get {
        return this.logonAsServiceFieldSpecified;
      }
      set {
        this.logonAsServiceFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType UpdateIfExists {
      get {
        return this.updateIfExistsField;
      }
      set {
        this.updateIfExistsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UpdateIfExistsSpecified {
      get {
        return this.updateIfExistsFieldSpecified;
      }
      set {
        this.updateIfExistsFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType PasswordExpired {
      get {
        return this.passwordExpiredField;
      }
      set {
        this.passwordExpiredField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PasswordExpiredSpecified {
      get {
        return this.passwordExpiredFieldSpecified;
      }
      set {
        this.passwordExpiredFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Disabled {
      get {
        return this.disabledField;
      }
      set {
        this.disabledField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DisabledSpecified {
      get {
        return this.disabledFieldSpecified;
      }
      set {
        this.disabledFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType CreateUser {
      get {
        return this.createUserField;
      }
      set {
        this.createUserField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateUserSpecified {
      get {
        return this.createUserFieldSpecified;
      }
      set {
        this.createUserFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension", IsNullable = false)]
  public partial class XmlFile {

    private string idField;

    private string elementPathField;

    private string fileField;

    private string nameField;

    private string valueField;

    private XmlFileAction actionField;

    private YesNoType permanentField;

    private bool permanentFieldSpecified;

    private YesNoType preserveModifiedDateField;

    private bool preserveModifiedDateFieldSpecified;

    private string sequenceField;

    private XmlFileSelectionLanguage selectionLanguageField;

    private bool selectionLanguageFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ElementPath {
      get {
        return this.elementPathField;
      }
      set {
        this.elementPathField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string File {
      get {
        return this.fileField;
      }
      set {
        this.fileField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
      get {
        return this.valueField;
      }
      set {
        this.valueField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public XmlFileAction Action {
      get {
        return this.actionField;
      }
      set {
        this.actionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType Permanent {
      get {
        return this.permanentField;
      }
      set {
        this.permanentField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PermanentSpecified {
      get {
        return this.permanentFieldSpecified;
      }
      set {
        this.permanentFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType PreserveModifiedDate {
      get {
        return this.preserveModifiedDateField;
      }
      set {
        this.preserveModifiedDateField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PreserveModifiedDateSpecified {
      get {
        return this.preserveModifiedDateFieldSpecified;
      }
      set {
        this.preserveModifiedDateFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string Sequence {
      get {
        return this.sequenceField;
      }
      set {
        this.sequenceField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public XmlFileSelectionLanguage SelectionLanguage {
      get {
        return this.selectionLanguageField;
      }
      set {
        this.selectionLanguageField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SelectionLanguageSpecified {
      get {
        return this.selectionLanguageFieldSpecified;
      }
      set {
        this.selectionLanguageFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  public enum XmlFileAction {

    /// <remarks/>
    createElement,

    /// <remarks/>
    deleteValue,

    /// <remarks/>
    setValue,

    /// <remarks/>
    bulkSetValue,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  public enum XmlFileSelectionLanguage {

    /// <remarks/>
    XPath,

    /// <remarks/>
    XSLPattern,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/wix/UtilExtension", IsNullable = false)]
  public partial class XmlConfig {

    private XmlConfig[] xmlConfig1Field;

    private string[] textField;

    private string idField;

    private XmlConfigAction actionField;

    private bool actionFieldSpecified;

    private string elementIdField;

    private string elementPathField;

    private string fileField;

    private string nameField;

    private XmlConfigNode nodeField;

    private bool nodeFieldSpecified;

    private XmlConfigON onField;

    private bool onFieldSpecified;

    private YesNoType preserveModifiedDateField;

    private bool preserveModifiedDateFieldSpecified;

    private string sequenceField;

    private string valueField;

    private string verifyPathField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("XmlConfig")]
    public XmlConfig[] XmlConfig1 {
      get {
        return this.xmlConfig1Field;
      }
      set {
        this.xmlConfig1Field = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
      get {
        return this.textField;
      }
      set {
        this.textField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public XmlConfigAction Action {
      get {
        return this.actionField;
      }
      set {
        this.actionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ActionSpecified {
      get {
        return this.actionFieldSpecified;
      }
      set {
        this.actionFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ElementId {
      get {
        return this.elementIdField;
      }
      set {
        this.elementIdField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ElementPath {
      get {
        return this.elementPathField;
      }
      set {
        this.elementPathField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string File {
      get {
        return this.fileField;
      }
      set {
        this.fileField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public XmlConfigNode Node {
      get {
        return this.nodeField;
      }
      set {
        this.nodeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NodeSpecified {
      get {
        return this.nodeFieldSpecified;
      }
      set {
        this.nodeFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public XmlConfigON On {
      get {
        return this.onField;
      }
      set {
        this.onField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OnSpecified {
      get {
        return this.onFieldSpecified;
      }
      set {
        this.onFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public YesNoType PreserveModifiedDate {
      get {
        return this.preserveModifiedDateField;
      }
      set {
        this.preserveModifiedDateField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PreserveModifiedDateSpecified {
      get {
        return this.preserveModifiedDateFieldSpecified;
      }
      set {
        this.preserveModifiedDateFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string Sequence {
      get {
        return this.sequenceField;
      }
      set {
        this.sequenceField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
      get {
        return this.valueField;
      }
      set {
        this.valueField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VerifyPath {
      get {
        return this.verifyPathField;
      }
      set {
        this.verifyPathField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  public enum XmlConfigAction {

    /// <remarks/>
    create,

    /// <remarks/>
    delete,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  public enum XmlConfigNode {

    /// <remarks/>
    element,

    /// <remarks/>
    value,

    /// <remarks/>
    document,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/wix/UtilExtension")]
  public enum XmlConfigON {

    /// <remarks/>
    install,

    /// <remarks/>
    uninstall,
  }
}